name: cp2077_red_cli
description: A tool to bundle scripts of a mod for Cyberpunk 2077.
version: 0.4.0
repository: https://github.com/rayshader/cp2077-red-cli

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^4.0.7
  args: ^2.5.0
  async: ^2.11.0
  chalkdart: ^3.0.5
  path: ^1.9.0
  rxdart: ^0.28.0
  toml: ^0.16.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
