name: cp2077_red_cli
description: A tool to bundle scripts of a mod for Cyberpunk 2077.
version: 0.2.0
repository: https://github.com/rayshader/cp2077-red-cli

environment:
  sdk: ^3.2.5

dependencies:
  archive: ^3.6.1
  args: ^2.4.2
  chalkdart: ^2.2.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
