name: cp2077_red_cli
description: A tool to bundle scripts of a mod for Cyberpunk 2077.
version: 0.5.0
repository: https://github.com/rayshader/cp2077-red-cli

environment:
  sdk: ^3.8.1

dependencies:
  archive: ^4.0.7
  args: ^2.7.0
  async: ^2.13.0
  chalkdart: ^3.0.5
  path: ^1.9.1
  rxdart: ^0.28.0
  toml: ^0.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
